---
title: "ARIMA"
output: html_document
---

```{r}
source("data_cleaning_and_dependencies.R")
```

# ARMA
```{r}
## 1. auto.arima fit
# no differencing applied (stationary = TRUE)
fit_stat <- auto.arima(train_ts, seasonal = TRUE, stationary = TRUE)

# differencing applied (stationary = FALSE) ;default
fit_nonstat <- auto.arima(train_ts, seasonal = TRUE, stationary = FALSE)

summary(fit_stat)
summary(fit_nonstat)
```


# ARIMA Analysis
```{r}
## 1. auto.arima fit
# no differencing applied (stationary = TRUE)
fit_stat <- auto.arima(train_ts, seasonal = TRUE, stationary = TRUE)
summary(fit_stat)
```

```{r}
# differencing applied (stationary = FALSE) ;default
fit_nonstat <- auto.arima(train_ts, seasonal = TRUE, stationary = FALSE)
summary(fit_nonstat)

# BASELINE MODEL: ARIMA(1,1,3)(1,0,2)[12] 
```

## ARIMA Training
```{r}
## 2. arima fit (perturbed values from auto.arima)

# ARIMA(1,1,2)(1,0,2)[12] 
fit1 <- Arima(train_ts, order = c(1,1,2),
              seasonal = list(order = c(1,0,2), period = 12), method = "ML")

# ARIMA(1,1,3)(1,0,1)[12] 
fit2 <- Arima(train_ts, order = c(1,1,3),
              seasonal = list(order = c(1,0,1), period = 12), method = "ML")

# ARIMA(1,1,2)(1,0,1)[12] 
fit3 <- Arima(train_ts, order = c(1,1,2),
              seasonal = list(order = c(1,0,1), period = 12), method = "ML")

# ARIMA(0,1,3)(1,0,2)[12] 
fit4 <- Arima(train_ts, order = c(0,1,3),
              seasonal = list(order = c(1,0,2), period = 12), method = "ML")

# ARIMA(1,1,1)(1,0,2)[12] 
fit5 <- Arima(train_ts, order = c(1,1,1),
              seasonal = list(order = c(1,0,2), period = 12), method = "ML")

# ARIMA(2,1,3)(1,0,2)[12] 
fit6 <- Arima(train_ts, order = c(2,1,3),
              seasonal = list(order = c(1,0,2), period = 12), method = "ML")
```


## ARIMA Forecasting Function
```{r}
## 3. moving 1-step ahead forecasts for holdout set

# computes moving 1-step ahead forecasts using fitted ARIMA models
arma_fc <- function(tsdata, ntrain, order, seasonal, method,
                    traincoef, include.mean, iprint=FALSE)
{ 
  obj <- arima(tsdata, 
              order=order, 
              seasonal=seasonal,
              init=traincoef, 
              fixed=traincoef,
              method=method, 
              include.mean=include.mean,
              optim.control=list(maxit=0))
  
  fc <- tsdata - obj$residuals
  ntotal <- length(tsdata)
  
  holdout_fc <- fc[(ntrain+1):ntotal]
  holdout <- tsdata[(ntrain+1):ntotal]
  
  if(iprint) print(cbind(holdout, holdout_fc))
  
  rmse <- sqrt(mean((holdout - holdout_fc)^2))
  
  list(rmse=rmse, fc=holdout_fc, residuals=obj$residuals)
}
```

# ARIMA Forecasting Results
```{r}
# find arima orders for all models, list
model_list <- list(
  fit_nonstat = fit_nonstat,
  fit1 = fit1,
  fit2 = fit2,
  fit3 = fit3,
  fit4 = fit4,
  fit5 = fit5,
  fit6 = fit6
)
arima_orders <- lapply(model_list, arimaorder)

# apply arma_fc to each model
fc_results <- lapply(seq_along(model_list), function(i) {
  fit_i <- model_list[[i]]
  ord_i <- arima_orders[[i]]
  
  arma_fc(
    tsdata = unempl_ts,
    ntrain = n_train,
    order = c(ord_i[1], ord_i[2], ord_i[3]),
    seasonal = list(order = c(ord_i[4], ord_i[5], ord_i[6]), period = ord_i[7]),
    method = "ML",
    traincoef = fit_i$coef,
    include.mean = FALSE,
    iprint = FALSE
  )
})

names(fc_results) <- names(arima_orders)

# extract RMSE values
rmse_vals <- sapply(fc_results, function(x) x$rmse)
```


**All ARIMA Models**
```{r}

## 4. tidy AIC and RMSE results into table
library(knitr)

rmse_table <- data.frame(
  model_name = c(
    "auto.arima: (1,1,3)(1,0,2)[12]",
    "(1,1,2)(1,0,2)[12]",
    "(1,1,3)(1,0,1)[12]",
    "(1,1,2)(1,0,1)[12]",
    "(0,1,3)(1,0,2)[12]",
    "(1,1,1)(1,0,2)[12]",
    "(2,1,3)(1,0,2)[12]"
  ),
  AIC = sapply(model_list, AIC),
  RMSE = rmse_vals,
  row.names = NULL
)

kable(rmse_table, digits = 3)
```


